# Activity rules — declarative per-activity configuration consumed by the
# muhurta scorer. Each entry describes what a given activity wants or avoids;
# the scorer reads these and applies bonuses/skips accordingly.
#
# Fields:
#   label                   human-readable name (MCP errors, UI dropdown)
#   skip_on_yoga            day omitted if any of these special yogas are active
#   skip_on_sankramana      omit slots overlapping the 16+16 ghati sankramana window
#   skip_on_khar_maasa      omit when Sun is in Dhanu or Meena
#   skip_on_adhika          omit during intercalary (Adhika) months
#   skip_on_pitru_paksha    omit during Bhadrapada Krishna paksha
#   skip_on_simha_stha_guru hard-skip for wedding while Jupiter is in Simha
#   penalty_on_simha_stha_shukra  soft score penalty when Venus is in Simha
#   skip_on_combust         list of planets ['Guru', 'Shukra'] — skip if combust
#   skip_on_panchaka_nakshatra   skip when day nakshatra is a Panchaka nakshatra
#   prefer_choghadiya       (block_name, bonus) — bonus when slot's block matches
#   prefer_tithi_class      Nanda|Bhadra|Jaya|Rikta|Purna — +1 when tithi matches
#   prefer_vara             list of vaaram names — +1 on matching weekday
#   prefer_lagna_class      Sthira|Chara|Dvisvabhava — +1 when rising sign matches
#   prefer_bhadra_puchha    bonus when slot overlaps Bhadra Puchha
#   prefer_nakshatra_mukha  ([classes], bonus) — bonus when day nakshatra mukha matches
#   avoid_karana            karana names — slots overlapping these are cut

_SAMSKARA_SKIP = ('Visha Yoga', 'Dagdha Yoga')

ACTIVITY_RULES: dict[str, dict] = {
    # — Generic —
    'any':           {'label': 'Anything auspicious'},
    'travel':        {'label': 'Travel / journey',
                      'avoid_karana': ['Vishti'],
                      'prefer_lagna_class': 'Chara',
                      'prefer_nakshatra_mukha': (['Tiryan'], 1)},
    'purchase':      {'label': 'Purchase (general)',
                      'prefer_choghadiya': ('Labh', 1)},
    'ceremony':      {'label': 'Ceremony / puja (general)',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'skip_on_sankramana': True,
                      'skip_on_khar_maasa': True,
                      'skip_on_adhika': True,
                      'skip_on_pitru_paksha': True,
                      'prefer_vara': ['Somavaram', 'Guruvaram']},
    'beginning':     {'label': 'New beginning (general)',
                      'prefer_choghadiya': ('Amrit', 1),
                      'prefer_tithi_class': 'Nanda',
                      'prefer_vara': ['Budhavaram', 'Guruvaram']},
    # — Samskaras —
    'wedding':       {'label': 'Wedding (Vivaha)',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'skip_on_sankramana': True,
                      'skip_on_khar_maasa': True,
                      'skip_on_adhika': True,
                      'skip_on_pitru_paksha': True,
                      'skip_on_simha_stha_guru': True,
                      'penalty_on_simha_stha_shukra': -2,
                      'skip_on_combust': ['Guru', 'Shukra'],
                      'prefer_tithi_class': 'Purna',
                      'prefer_vara': ['Guruvaram', 'Somavaram'],
                      'prefer_lagna_class': 'Sthira'},
    'engagement':    {'label': 'Engagement (Nischayam)',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'skip_on_sankramana': True,
                      'skip_on_khar_maasa': True,
                      'skip_on_adhika': True,
                      'skip_on_pitru_paksha': True,
                      'prefer_tithi_class': 'Purna',
                      'prefer_vara': ['Guruvaram', 'Somavaram'],
                      'prefer_lagna_class': 'Sthira'},
    'naming':        {'label': 'Naming (Namakaranam)',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'skip_on_sankramana': True,
                      'skip_on_khar_maasa': True,
                      'skip_on_adhika': True,
                      'skip_on_pitru_paksha': True,
                      'prefer_choghadiya': ('Shubh', 1),
                      'prefer_tithi_class': 'Nanda',
                      'prefer_vara': ['Budhavaram', 'Guruvaram'],
                      'prefer_lagna_class': 'Dvisvabhava'},
    'annaprasana':   {'label': 'Annaprasana (First feeding)',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'skip_on_sankramana': True,
                      'skip_on_khar_maasa': True,
                      'skip_on_adhika': True,
                      'skip_on_pitru_paksha': True,
                      'prefer_choghadiya': ('Shubh', 1),
                      'prefer_tithi_class': 'Bhadra',
                      'prefer_vara': ['Somavaram', 'Guruvaram'],
                      'prefer_lagna_class': 'Dvisvabhava'},
    'karnavedha':    {'label': 'Karnavedha (Ear-piercing)',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'skip_on_sankramana': True,
                      'skip_on_khar_maasa': True,
                      'skip_on_adhika': True,
                      'skip_on_pitru_paksha': True,
                      'prefer_tithi_class': 'Bhadra',
                      'prefer_vara': ['Budhavaram', 'Shukravaram'],
                      'prefer_lagna_class': 'Dvisvabhava'},
    'mundana':       {'label': 'Mundana / Chaula (First head-shave)',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'skip_on_sankramana': True,
                      'skip_on_khar_maasa': True,
                      'skip_on_adhika': True,
                      'skip_on_pitru_paksha': True,
                      'prefer_tithi_class': 'Nanda',
                      'prefer_vara': ['Budhavaram', 'Guruvaram'],
                      'prefer_lagna_class': 'Dvisvabhava'},
    'upanayana':     {'label': 'Upanayana (Sacred thread)',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'skip_on_sankramana': True,
                      'skip_on_khar_maasa': True,
                      'skip_on_adhika': True,
                      'skip_on_pitru_paksha': True,
                      'skip_on_combust': ['Guru', 'Shukra'],
                      'prefer_tithi_class': 'Nanda',
                      'prefer_vara': ['Budhavaram', 'Guruvaram'],
                      'prefer_lagna_class': 'Dvisvabhava'},
    'vidyarambha':   {'label': 'Education start (Vidyarambha)',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'skip_on_sankramana': True,
                      'skip_on_khar_maasa': True,
                      'skip_on_adhika': True,
                      'skip_on_pitru_paksha': True,
                      'prefer_choghadiya': ('Amrit', 1),
                      'prefer_tithi_class': 'Nanda',
                      'prefer_vara': ['Budhavaram'],
                      'prefer_lagna_class': 'Dvisvabhava'},
    'gruhapravesha': {'label': 'Gruhapravesha (Home entry)',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'skip_on_sankramana': True,
                      'skip_on_khar_maasa': True,
                      'skip_on_adhika': True,
                      'skip_on_pitru_paksha': True,
                      'prefer_tithi_class': 'Bhadra',
                      'prefer_vara': ['Guruvaram', 'Somavaram'],
                      'prefer_lagna_class': 'Sthira'},
    # — Acquisitions —
    'vehicle':       {'label': 'Vehicle purchase',
                      'prefer_choghadiya': ('Labh', 1),
                      'prefer_tithi_class': 'Bhadra',
                      'prefer_vara': ['Shukravaram'],
                      'prefer_lagna_class': 'Sthira'},
    'property':      {'label': 'Property / Land purchase',
                      'prefer_choghadiya': ('Labh', 1),
                      'prefer_tithi_class': 'Bhadra',
                      'prefer_vara': ['Guruvaram', 'Shukravaram'],
                      'prefer_lagna_class': 'Sthira'},
    'gold':          {'label': 'Gold / Jewelry purchase',
                      'prefer_choghadiya': ('Labh', 1),
                      'prefer_tithi_class': 'Bhadra',
                      'prefer_vara': ['Shukravaram', 'Guruvaram'],
                      'prefer_lagna_class': 'Sthira'},
    # — Construction & Ventures —
    'bhumi_puja':    {'label': 'Bhumi Puja / Foundation laying',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'prefer_tithi_class': 'Bhadra',
                      'prefer_vara': ['Guruvaram', 'Somavaram'],
                      'prefer_lagna_class': 'Sthira'},
    'business':      {'label': 'Business launch',
                      'prefer_choghadiya': ('Amrit', 1),
                      'prefer_tithi_class': 'Nanda',
                      'prefer_vara': ['Guruvaram', 'Budhavaram'],
                      'prefer_lagna_class': 'Sthira'},
    'job':           {'label': 'Job start / Contract signing',
                      'prefer_choghadiya': ('Amrit', 1),
                      'prefer_tithi_class': 'Nanda',
                      'prefer_vara': ['Guruvaram', 'Budhavaram'],
                      'prefer_lagna_class': 'Sthira'},
    # — Spiritual —
    'yajna':         {'label': 'Yajna / Homam',
                      'skip_on_yoga': list(_SAMSKARA_SKIP),
                      'prefer_tithi_class': 'Purna',
                      'prefer_vara': ['Guruvaram', 'Somavaram'],
                      'prefer_lagna_class': 'Sthira'},
    'pilgrimage':    {'label': 'Pilgrimage (Tirtha Yatra)',
                      'avoid_karana': ['Vishti'],
                      'prefer_lagna_class': 'Chara'},
    # — Civil & Medical —
    'court':         {'label': 'Court / legal matter',
                      'prefer_tithi_class': 'Jaya',
                      'prefer_vara': ['Mangalavaram']},
    'litigation':    {'label': 'Litigation / contest',
                      'prefer_tithi_class': 'Jaya',
                      'prefer_vara': ['Mangalavaram'],
                      'prefer_bhadra_puchha': 2},
    'surgery':       {'label': 'Surgery / medical procedure',
                      'avoid_karana': ['Vishti'],
                      'prefer_vara': ['Mangalavaram']},
    # — Panchaka-restricted activities —
    'cremation':         {'label': 'Cremation rites',
                          'skip_on_panchaka_nakshatra': True},
    'construction_roof': {'label': 'Roof-laying / construction milestone',
                          'skip_on_panchaka_nakshatra': True},
    'wood_cutting':      {'label': 'Wood-cutting',
                          'skip_on_panchaka_nakshatra': True},
    # — Nakshatra Mukha (mouth-direction) activity rules —
    'well_digging':      {'label': 'Well / foundation digging',
                          'prefer_nakshatra_mukha': (['Adho'], 1)},
    'coronation':        {'label': 'Coronation / title ceremony',
                          'skip_on_yoga': list(_SAMSKARA_SKIP),
                          'prefer_nakshatra_mukha': (['Urdhva'], 1)},
}

ACTIVITIES = tuple(ACTIVITY_RULES.keys())
